### ISSUE TITLE
Additional text files and stuff to translate

### ISSUE THREAD

**Issue by ShadowDuke** [MasterPaw/OW_FrenchPatch#31]
Hey there. Just wanted to inform you, theres more text you need to consider, not only the text-*.xml files.
Im working on a german translation and found out, that even the other files have content that needs to be translated.
For example, height.xml, copy it and rename to height-change.xml and translate the <*zName> strings as well. E.g. Flat, Ocean, Lake, etc.

Cheers

**Comment by MasterPaw** [comment]
Yes thanks,
we noticed it, I asked about it and Devs said they were parsing files to externalize them to text specifics files for translation
We also have to convert the mod to a translation mod which is a new thing since latest patch

**Comment by ShadowDuke** [comment]
Yes, i know about the "translation" dir and things, but its not working properly. Easiest way for me now is using it still "like a mod" but also continuing translating.

Looking at all the files and have done a lot translations already for several games (and engines), this could be done a lot easier. Just saying. ;)

**Comment by MasterPaw** [comment]
well if you have suggestion you could post them in community-based-translation channel of the discord for the devs
